name: My first Job
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.url.outputs.preview-url  }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup Node In Machine
        uses: actions/setup-node@v4
        with:
          node-version: 'v18.19.0'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: remove unrequired files
        run: |
          rm -rf src
          rm -rf tsconfig.json
          rm -rf .gitignore
          rm -rf .gtihub
          rm -rf dikh.yaml
          rm -rf dikahnekeliye.json
      - name: production_modules
        run: npm run prod_module
      - name: check folder
        run: tree -h -L 1
      - name: check size
        run: tree --du -ahF dist/ | grep "\(files\|/\)$"
      - name: deploye to vercel
        uses: amondnet/vercel-action@v20
        id: url
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-args: '--prod'
      - name: deployed url
        run: echo "Deployed to ${{ toJson(steps.url.outputs) }}"
      

  healthcheck:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: health check
        run: |
          # Perform the curl request and store the status code in a variable
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${{needs.build.outputs.url}} )

          # Check if the status code is 200 (OK)
          if [ $STATUS_CODE -eq 200 ]; then
            echo "Success: Status code is 200"
            # Exit with success code
            exit 0
          else
            echo "Failed: Status code is $STATUS_CODE"
            # Exit with failure code
            exit 1
          fi

        



